[tr]
  [td]NAME[/td]
[/tr]
[tr]
  [td][/td][td][b]nmap[/b] - Network exploration tool and security / port scanner (**)[/td]
[/tr]
[tr]
  [td]SYNOPSIS[/td]
[/tr]
[tr]
  [td][/td][td]nmap IP[/td]
[/tr]
[tr]
  [td]EXAMPLE[/td]
[/tr]
[tr]
  [td][/td][td][b]nmap 127.0.0.1[/b][/td]
[/tr]
[tr]
  [td]AUTHOR[/td][td][/td]
[/tr]
[tr]
  [td][/td][td]Written by Mario Chorvath[/td]
[/tr]
[tr]
  [td]COPYRIGHT[/td][td][/td]
[/tr]
[tr]
  [td][/td][td]Mario Chorvath. License GPLv2: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl.html&gt;.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
  Original nmap author http://nmap.org/book/
  [/td]
[/tr]
